#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    'cons',
    'mozChromeDir',
);


$cons->InstallInChrome('debugging-languages.xml');
$cons->InstallInChrome('debugging-properties-overlay.xul');
$cons->InstallInChrome('debugging-properties.xul');
$cons->InstallInChrome('debugging-properties.js');
