#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    "cons",
    "mozChromeDir",
    "supportDir",
);

$cons->InstallWriteable("$supportDir/samples/python_tutorials", "content.types");
$cons->InstallWriteable("$supportDir/samples/python_tutorials", "python_tutorial.komodoproject");
$cons->InstallWriteable("$supportDir/samples/python_tutorials", "preprocess.py");
$cons->InstallWriteable("$supportDir/samples/python_tutorials", "contenttype.py");
$cons->InstallWriteable("$supportDir/samples/python_tutorials", "helloworld.html");
$cons->InstallWriteable("$supportDir/samples/python_tutorials", "helloworld.py");

