#!/usr/local/bin/perl

# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    'cons',
    'platform',
    'mozChromeDir',
    'unsiloedPythonExe',
    'jarring',
    'productType',
    'unsiloedPythonExe',
    'buildFlavour',
    'mozVersion',
    'withDebugging',
);

if ($withDebugging) {
    $cons->InstallInChrome('debugger.css');
}
$cons->InstallInChrome('buttons.css');
$cons->InstallInChrome('colorpicker.css');
$cons->InstallInChrome('findbar.css');
$cons->InstallInChrome('listbox.css');
$cons->InstallInChrome('scintilla.css');
$cons->Preprocess('widgets.p.css', 'widgets.css');
$cons->InstallInChrome('widgets.css');
$cons->InstallInChrome('prefwidgets.css');
$cons->Preprocess('views.p.css', 'views.css');
$cons->InstallInChrome('views.css');
$cons->InstallInChrome('partviewer.css');
$cons->InstallInChrome('keybinding.css');
