#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    'cons',
    'mozChromeDir',
    'platform',
    'productType',
    'buildFlavour',
    'unsiloedPythonExe',
    'mozVersion',
);

$cons->InstallInChrome('filebrowser.xul');
$cons->Preprocess("filebrowser.p.js", "filebrowser.js");
$cons->InstallInChrome('filebrowser.js');
$cons->InstallInChrome('filebrowseview.js');

