/* Copyright (c) 2017 ActiveState Software Inc.
   See the file LICENSE.txt for licensing information. */

#include "nsISupports.idl"
interface koIAsyncCallback;

[scriptable, uuid(0a2b6060-5366-4976-947c-2ffbd7a3676f)]
interface koICodeintelLegacy: nsISupports {

    void getLanguages(in koIAsyncCallback callback);

    void getCompletions(in AString buf,
                in long caretPos,
                in AString path,
                in AString parentPath,
                in AString importPaths,
                in AString languageName,
                in long limit,
                in koIAsyncCallback callback);

    void getDefinition(in AString buf,
                in long caretPos,
                in AString path,
                in AString parentPath,
                in AString importPaths,
                in AString language,
                in koIAsyncCallback callback);

    void getSymbolsInBuffer(in AString buf,
                in long caretLine,
                in long caretPos,
                in AString indentString,
                in AString languageName,
                in AString sortOrder,
                in koIAsyncCallback callback);

    void getCaretScope(in AString buf,
                in long caretLine,
                in long caretPos,
                in AString languageName,
                in koIAsyncCallback callback);

};
