#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.

Import(
    'cons',
    'build',
    'ranRegxpcomStateFileName',
    'mozComponentsDir',
    'mozIdlIncludePath',
    'idlExportDir',
    'komodoPythonUtilsDir',
    'unsiloedPythonExe',
    'siloedPython',
    'supportDir',
    'mozVersion',
    'sdkDir',
    'mozSrc',
    'platform',
    'havePy2to3',
);

$cons->Install($idlExportDir, 'koILinter.idl');
$cons->BuildAndInstallXpt('koILinter.idl');

$cons->InstallPythonUtility('koLintResult.py');
$cons->InstallXpcomComponent('koPerlCompileLinter.py');
$cons->InstallXpcomComponent('koPythonLinter.py');
$cons->Install("$supportDir/python", 'pycompile.py');
if ($havePy2to3) {
    $cons->Py2To3('pycompile.py', "$supportDir/python/py3compile.py");
}
$cons->InstallXpcomComponent('koCSSExLinter.py');
$cons->InstallXpcomComponent('koHTMLLinter.py');
$cons->InstallXpcomComponent('koPHPLinter.py');
$cons->InstallXpcomComponent('koESLintLinter.py'); 
$cons->InstallXpcomComponent('koTclLinter.py');
$cons->InstallXpcomComponent('koJavaScriptLinter.py');
$cons->InstallXpcomComponent('koLintService.py');
$cons->InstallPythonUtility('koLintResults.py');

if ($platform eq "win") {
    $cons->Install("$supportDir/perl/perltray", 'PerlTray.pm');
}
    
