#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    'cons',
    'build',
    'platform',
    'ranRegxpcomStateFileName',
    'mozComponentsDir',
    'mozIdlIncludePath',
    'idlExportDir',
    'komodoPythonUtilsDir',
    'supportDir',
    'unsiloedPythonExe',
    'productType',
    'buildFlavour',
    'mozVersion',
    'sdkDir',
    'mozSrc',
    'withSCC',
    'withWatchdogFSNotifications',
);

# Examples
#$cons->Preprocess('URIlib.unprocessed.py', 'URIlib.py');
#$cons->InstallPythonUtility('URIlib.py');

$cons->Install($idlExportDir, 'koIFileNotificationService.idl');
$cons->BuildAndInstallXpt('koIFileNotificationService.idl');
$cons->InstallXpcomComponent('koFileNotificationService.py');

$cons->InstallPythonUtility('osFilePollingNotifier.py');
$cons->InstallPythonUtility('osFileNotificationUtils.py');

$cons->Preprocess('fileStatusUtils.p.py', 'fileStatusUtils.py');
$cons->InstallPythonUtility('fileStatusUtils.py');

if ($withWatchdogFSNotifications) {
    $cons->InstallPythonUtility('watchdogFileNotifications.py');
    $cons->InstallPythonUtility('watchdog_patches.py');
}
