#!/usr/local/bin/perl
# Copyright (c) 2009 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.

Import(
    'cons',
    'platform',
    'productType',
    'buildFlavour',
    'sdkDir',
    'idlExportDir',
    'build',
    'mozBin',
    'unsiloedPythonExe',
    'mozVersion',
    'mozExtensionDir',
    'mozIdlIncludePath',
);


$cons->KoExt("koinstall");
