#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    "cons",
    "komodoPerlUtilsDir"
);

$cons->Install("$komodoPerlUtilsDir/Net", "Cmd.pm");
$cons->Install("$komodoPerlUtilsDir/Net", "Config.pm");
$cons->Install("$komodoPerlUtilsDir/Net", "FTP.pm");

