#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    'cons',
    'mozChromeDir',
    'platform',
    'productType',
    'buildFlavour',
    'unsiloedPythonExe',
    'mozVersion',
    'withSCC',
    'withDebugging',
);

$cons->InstallInChrome('scrolltabs.xml');
$cons->InstallInChrome('buttons.xml');
$cons->InstallInChrome('listbox.xml');
$cons->InstallInChrome('colorpicker.xml');
$cons->Preprocess('scintilla.p.xml', 'scintilla.xml');
$cons->InstallInChrome('scintilla.xml');
$cons->Preprocess('scintilla-overlay.p.xul', 'scintilla-overlay.xul');
$cons->InstallInChrome('scintilla-overlay.xul');
$cons->InstallInChrome('text-link.xml');
$cons->InstallInChrome('widgets.xml');
$cons->Preprocess('views.p.xml', 'views.xml');
$cons->InstallInChrome('views.xml');
$cons->InstallInChrome('views-tabbed.xml');
$cons->InstallInChrome('views-browser.xml');
$cons->InstallInChrome('views-xul.xml');
$cons->Preprocess('views-editor.p.xml', 'views-editor.xml');
$cons->InstallInChrome('views-editor.xml');
$cons->Preprocess('views-buffer.p.xml', 'views-buffer.xml');
$cons->InstallInChrome('views-buffer.xml');
$cons->Preprocess('views-diff.p.xml', 'views-diff.xml');
$cons->InstallInChrome('views-diff.xml');
$cons->InstallInChrome('views-multi.xml');
$cons->Preprocess('views-terminal.p.xml', 'views-terminal.xml');
$cons->InstallInChrome('views-terminal.xml');
$cons->Preprocess('views-minimap.p.xml', 'views-minimap.xml');
$cons->InstallInChrome('views-minimap.xml');
$cons->InstallInChrome('views-findresults.xml');
$cons->InstallInChrome('pane.xml');
$cons->InstallInChrome('toolbar.xml');
$cons->Preprocess('windows.p.xml', 'windows.xml');
$cons->InstallInChrome('windows.xml');
$cons->Preprocess('wizard.p.xml', 'wizard.xml');
$cons->InstallInChrome('wizard.xml');
$cons->InstallInChrome('menu.xml');
