#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    'cons',
    'komodoPythonUtilsDir',
    'ranRegxpcomStateFileName',
    'platform',
    'buildType',
    'mozVersion',
    'productType',
    'unsiloedPythonExe',
    'buildFlavour',
    'siloedPythonVersion',
    'supportDir',
    'mozVersion',
);

my $siloedPythonMajor;
my $siloedPythonMinor;
if ($siloedPythonVersion =~ /^(\d+)\.(\d+)/) {
    $siloedPythonMajor = $1;
    $siloedPythonMinor = $2;
}

$cons->InstallPythonUtility('uriparse.py');
$cons->InstallPythonUtility('HTMLTreeParser.py');
$cons->InstallPythonUtility('koXMLDatasetInfo.py');
$cons->InstallPythonUtility('koXMLTreeService.py');
$cons->InstallPythonUtility('koCatalog.py');
$cons->InstallPythonUtility('koSimpleLexer.py');
$cons->InstallPythonUtility('koDTD.py');
$cons->InstallPythonUtility('kotaclib.py');
$cons->InstallPythonUtility('koRNGElementTree.py');
$cons->InstallPythonUtility('koUnicodeEncoding.py');
$cons->InstallPythonUtility('eollib.py');
$cons->InstallPythonUtility('strptime.py');
$cons->InstallPythonUtility('koXMLPrefs.py');
$cons->InstallPythonUtility('process.py');
$cons->InstallPythonUtility('koprocessutils.py');
$cons->InstallPythonUtility('which.py');
$cons->Preprocess('koTreeView.p.py', 'koTreeView.py');
$cons->InstallPythonUtility('koTreeView.py');
$cons->InstallPythonUtility('lexregex.py');
$cons->InstallPythonUtility('pyxpcomProfiler.py');
$cons->InstallPythonUtility('reflow.py');
$cons->InstallPythonUtility('difflibex.py');
$cons->InstallPythonUtility('sitepyxpcom.py');
$cons->InstallPythonUtility('directoryServiceUtils.py');
$cons->InstallPythonUtility('applib.py');
$cons->InstallPythonUtility('textutils.py');
$cons->InstallPythonUtility('upgradeutils.py');
$cons->InstallPythonUtility('mozutils.py');
$cons->InstallPythonUtility('fileutils.py');
$cons->InstallPythonUtility('memutils.py');
$cons->InstallPythonUtility('thread_helper.py');

$cons->InstallPythonUtility('langinfo.py');
$cons->InstallPythonUtility('langinfo_binary.py');
$cons->InstallPythonUtility('langinfo_doc.py');
$cons->InstallPythonUtility('langinfo_komodo.py');
$cons->InstallPythonUtility('langinfo_mozilla.py');
$cons->InstallPythonUtility('langinfo_other.py');
$cons->InstallPythonUtility('langinfo_prog.py');
$cons->InstallPythonUtility('langinfo_template.py');
$cons->InstallPythonUtility('langinfo_tiny.py');
$cons->InstallPythonUtility('textinfo.py');
$cons->InstallPythonUtility('pythonVersionUtils.py');


if ($platform eq "win") {
    $cons->InstallPythonUtility('wininteg.py');
    $cons->InstallPythonUtility('ctypesutils.py');
    $cons->InstallPythonUtility('win32_named_pipe.py');
}

if ($buildFlavour eq "dev") {
    $cons->InstallPythonUtility('benchmark.py');
}
