#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    'cons',
    'platform',
    'readmeDir',
    'licenseTextType',
);

$cons->InstallAs("LICENSE.rtf", "LICENSE.$licenseTextType.rtf"); 
if ($platform eq "win") {
    $cons->InstallAs("$readmeDir/LICENSE.txt", "LICENSE.$licenseTextType.txt"); 
}

