#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    'cons',
    'build',
    'ranRegxpcomStateFileName',
    'mozComponentsDir',
    'mozIdlIncludePath',
    'idlExportDir',
    'komodoPythonUtilsDir',
    'sdkDir',
    'mozSrc',
    'mozVersion',
    'unsiloedPythonExe'
);


$cons->Install($idlExportDir, 'koIInvocation.idl');
$cons->BuildAndInstallXpt('koIInvocation.idl');
$cons->InstallXpcomComponent('koInvokeInterpreters.py');

$cons->InstallPythonUtility('invocationutils.py');
