#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    'cons',
    'build',
    'ranRegxpcomStateFileName',
    'mozComponentsDir',
    'mozIdlIncludePath',
    'idlExportDir',
    'mozBin',
    'mozVersion',
    'version',
    'buildNum',
    'buildType',
    'buildFlavour',
    'komodoPythonUtilsDir',
    'withSCC',
    'sdkDir',
    'mozSrc',
    'unsiloedPythonExe',
);

if ($withSCC) {
    $cons->InstallPythonUtility('svnlib.py');
    $cons->InstallXpcomComponent('koSVN.py');
}

