#!/usr/local/bin/perl
# Copyright (c) 2003-2008 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.

Import(
    "cons",
    "mozChromeDir",
    'platform',
    'productType',
    'buildFlavour',
    'unsiloedPythonExe',
    'mozVersion',
    'withSCC',
);

if ($withSCC) {
    $cons->InstallInChrome("overlay.xul");
    $cons->InstallInChrome("widget.xul");
    $cons->InstallInChrome("widget.js");
    $cons->InstallInChrome("log.xul");
    $cons->InstallInChrome("scc.js");
    $cons->InstallInChrome("commit.xul");
    $cons->InstallInChrome("commit.js");
    $cons->InstallInChrome("history.xul");
    $cons->InstallInChrome("history.js");
    $cons->InstallInChrome("checkout.xul");
    $cons->InstallInChrome("checkout.js");
    $cons->InstallInChrome("push.xul");
    $cons->InstallInChrome("push.js");
    $cons->InstallInChrome("bindings/svn_checkout.xml");
    $cons->InstallInChrome("bindings/cvs_checkout.xml");
}
