#!/usr/local/bin/perl
# Copyright (c) 2004-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    "cons",
    "mozChromeDir",
    "platform",
    "productType",
    "buildFlavour",
    "unsiloedPythonExe",
);

$cons->InstallInChrome("overlay.xul");

for my $part (qw/scimoz firefoxAutoComplete
               auto_indent_scimoz soft_chars
                refactoring/) {
    $cons->InstallInChrome("test_$part.xul");
    $cons->InstallInChrome("test_$part.js");
}
__END__
$cons->InstallInChrome("test_scimoz.xul");
$cons->InstallInChrome("test_scimoz.js");
$cons->InstallInChrome("test_firefoxAutoComplete.xul");
$cons->InstallInChrome("test_firefoxAutoComplete.js");

$cons->InstallInChrome("test_auto_indent_scimoz.xul");
$cons->InstallInChrome("test_auto_indent_scimoz.js");
$cons->InstallInChrome("test_soft_chars.xul");
$cons->InstallInChrome("test_soft_chars.js");
