#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    "cons",
    "komodoPerlUtilsDir",
    "supportDir",
);

$cons->Install($komodoPerlUtilsDir, "perl5db.pl");
$cons->Install($supportDir, "perl5db.pl");

