#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    "cons",
    "mozChromeDir",
    "supportDir",
);

$cons->InstallWriteable("$supportDir/samples/xslt_tutorials", "xslt_tutorial.komodoproject");
$cons->InstallWriteable("$supportDir/samples/xslt_tutorials", "mailexport.xml");
$cons->InstallWriteable("$supportDir/samples/xslt_tutorials", "mailexport2html.xsl");
$cons->InstallWriteable("$supportDir/samples/xslt_tutorials", "mailexport.html");
