#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    "cons",
    "komodoPerlUtilsDir",
);

$cons->Install("$komodoPerlUtilsDir/ASRemote", "Jacket.pm");
$cons->Install("$komodoPerlUtilsDir/ASRemote", "Variable.pm");
