#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    'cons',
    'platform',
    'mozChromeDir',
    'mozResourcesDir',
    'mozBin',
    'mozExe',
    'mozSrc',
    'unsiloedPythonExe',
    'productType',
    'jarring',
    'buildFlavour',
    'komodoTitleBarName',
    'mozVersion',
    'withHTTPInspector',
    'withSCC',
    'withSharedSupport',
    'withDebugging',
    'withRx',
    'withCodeBrowser',
    'sdkDir',
);

if ($jarring) {
    $cons->InstallAs("$mozChromeDir/xtk.manifest", "jarred.manifest");
} else {
    $cons->InstallAs("$mozChromeDir/xtk.manifest", "debug.manifest");
}
$cons->Command("xtk.manifest.landmark",
               "$mozChromeDir/xtk.manifest",
               "$mozBin/chrome.manifest",
               "$sdkDir/pylib/chromereg.py",
               "$mozExe",
               qq(
                 $unsiloedPythonExe %3 %2 %1 "chrome"
                 touch %>
               ));

$cons->InstallRecursive("$mozChromeDir/xtk/content/",
                        cwd()."/src/chrome/xtk/content/",
                        ('\.svn'));
if (-d "src/chrome/xtk/locale") {
    $cons->InstallRecursive("$mozChromeDir/xtk/locale/",
                            cwd()."/src/chrome/xtk/locale/",
                            ('\.svn'));
}
if (-d "src/chrome/xtk/skin") {
    $cons->InstallRecursive("$mozChromeDir/xtk/skin/",
                            cwd()."/src/chrome/xtk/skin/",
                            ('\.svn'));
}

