#!/usr/local/bin/perl
# Copyright (c) 2000-2006 ActiveState Software Inc.
# See the file LICENSE.txt for licensing information.


Import(
    "cons",
    "mozChromeDir",
    "supportDir",
    "komodoDevDir",
    "platform",
    "unsiloedPythonExe",
    "productType",
    "buildFlavour",
    "mozVersion",
    "withDebugging",
    "withCodeBrowser",
);
$cons->InstallRecursive("$supportDir/tools", "$komodoDevDir/src/tools");

